# Numpy

In [1]:
import numpy as np

In [2]:
ar1=np.array([1,2,3,4,5])

In [3]:
type(ar1)

numpy.ndarray

In [4]:
ar1

array([1, 2, 3, 4, 5])

In [5]:
# 2D array
ar_2D=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [6]:
ar_2D

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [7]:
l1 = [1,2,4,6,8]

In [8]:
ar2=np.array(l1)

In [9]:
type(ar2)

numpy.ndarray

In [10]:
t1=(1,2,3,4,5)

In [11]:
type(t1)

tuple

In [12]:
ar3=np.array(t1)

In [13]:
type(ar3)

numpy.ndarray

In [14]:
ar3

array([1, 2, 3, 4, 5])

In [15]:
print(dir(ar1))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__',

In [16]:
ar4=np.arange(0,21,2)
ar4

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [17]:
ar5=np.linspace(1,20,10,dtype=int)
ar5

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 20])

In [18]:
np.random.random(20)

array([0.81378442, 0.2497035 , 0.45156559, 0.58340031, 0.71865958,
       0.72395574, 0.97612887, 0.64214015, 0.60989423, 0.04707872,
       0.08569817, 0.29650424, 0.56829232, 0.65506538, 0.77699701,
       0.94886693, 0.78631255, 0.40654094, 0.09905749, 0.40292269])

In [19]:
np.random.randint(1,20,10)

array([15, 17, 16,  8,  6, 10, 14, 10,  9,  9])

In [20]:
ar1

array([1, 2, 3, 4, 5])

In [21]:
ar5=np.arange(1,21)

In [22]:
ar5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [23]:
ar5_2D=np.reshape(ar5,(5,4))

In [24]:
ar5_2D

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [25]:
ar5_3D=np.reshape(ar5,(2,5,2))

In [26]:
ar5_3D

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [27]:
ar5_2D

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [28]:
np.transpose(ar5_2D)

array([[ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19],
       [ 4,  8, 12, 16, 20]])

## Inspection of arrays

In [29]:
ar5_2D.shape

(5, 4)

In [30]:
ar5_2D.size

20

In [31]:
ar5_2D

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [32]:
ar5_2D.ndim

2

In [33]:
ar1

array([1, 2, 3, 4, 5])

In [34]:
ar1.ndim

1

In [35]:
ar5_3D

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [36]:
ar5_3D.ndim

3

In [37]:
ar5_3D.dtype

dtype('int32')

In [38]:
ar5_3D.nbytes

80

## Accessing elements 

In [39]:
ar1

array([1, 2, 3, 4, 5])

In [40]:
ar1[0]

1

In [41]:
ar1[1]

2

In [42]:
ar1[-1]

5

In [43]:
ar5_2D

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [44]:
ar5_2D[2,2]

11

In [45]:
ar5_2D[4,3]

20

In [46]:
ar5_2D[2,1]

10

In [47]:
ar1

array([1, 2, 3, 4, 5])

In [48]:
ar1[1:4]

array([2, 3, 4])

In [49]:
ar5_2D

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [50]:
ar5_2D[1,1:3]

array([6, 7])

In [51]:
ar1

array([1, 2, 3, 4, 5])

In [52]:
ar1[:]

array([1, 2, 3, 4, 5])

In [53]:
ar5_2D[:,1]

array([ 2,  6, 10, 14, 18])

In [54]:
ar1

array([1, 2, 3, 4, 5])

In [55]:
ar1[::3]

array([1, 4])

In [56]:
ar5_2D

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [57]:
ar5_2D[:,0::3]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12],
       [13, 16],
       [17, 20]])

In [58]:
ar5_2D[:,3]

array([ 4,  8, 12, 16, 20])

In [59]:
ar5_2D

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [60]:
# Last row 
ar5_2D[4::,::]

array([[17, 18, 19, 20]])

In [61]:
# 10,11,14,15
ar5_2D[2:4,1:3]

array([[10, 11],
       [14, 15]])

In [62]:
#10,11,12,13,14,15
ar5_2D[2:4,1:4]

array([[10, 11, 12],
       [14, 15, 16]])

## Update

In [63]:
ar1

array([1, 2, 3, 4, 5])

In [64]:
ar1[1]=21

In [65]:
ar1

array([ 1, 21,  3,  4,  5])

## Mathematical operations

In [66]:
ar1

array([ 1, 21,  3,  4,  5])

In [67]:
ar1+5

array([ 6, 26,  8,  9, 10])

In [68]:
ar1-5

array([-4, 16, -2, -1,  0])

In [69]:
ar1*3

array([ 3, 63,  9, 12, 15])

In [70]:
ar1

array([ 1, 21,  3,  4,  5])

In [71]:
ar2

array([1, 2, 4, 6, 8])

In [72]:
ar1+ar2

array([ 2, 23,  7, 10, 13])

In [73]:
ar5_2D

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [74]:
ar5_2D*2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40]])

In [75]:
ar7=[1,2,3,4]

In [76]:
ar5_2D+ar7

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12],
       [10, 12, 14, 16],
       [14, 16, 18, 20],
       [18, 20, 22, 24]])

In [77]:
ar1.sum()

34

In [78]:
ar1

array([ 1, 21,  3,  4,  5])

In [79]:
ar1.mean()

6.8

In [80]:
ar1.min()

1

In [81]:
ar1.max()

21

In [82]:
ar5_2D

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [83]:
ar5_2D.sum()

210

In [84]:
ar5_2D[:,-1].sum()

60

In [85]:
ar5_2D[0,:].mean()

2.5

In [86]:
ar5_2D[ar5_2D>=10]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [87]:
ar5_2D[(ar5_2D>=10) & (ar5_2D<=15)]

array([10, 11, 12, 13, 14, 15])

In [88]:
ar5_2D[ar5_2D%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

## Merging arrays

In [89]:
ar1

array([ 1, 21,  3,  4,  5])

In [90]:
ar2

array([1, 2, 4, 6, 8])

In [91]:
np.concatenate((ar1,ar2))

array([ 1, 21,  3,  4,  5,  1,  2,  4,  6,  8])

In [92]:
np.concatenate((ar1,ar2))

array([ 1, 21,  3,  4,  5,  1,  2,  4,  6,  8])

In [93]:
np.vstack((ar1,ar2))

array([[ 1, 21,  3,  4,  5],
       [ 1,  2,  4,  6,  8]])

In [94]:
np.hstack((ar1,ar2))

array([ 1, 21,  3,  4,  5,  1,  2,  4,  6,  8])

In [95]:
np.full((3,3,),10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [96]:
np.zeros((4,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [97]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [98]:
ar10=np.empty((4,4))

In [99]:
ar10.fill(20)

In [100]:
ar10

array([[20., 20., 20., 20.],
       [20., 20., 20., 20.],
       [20., 20., 20., 20.],
       [20., 20., 20., 20.]])

In [101]:
ar1

array([ 1, 21,  3,  4,  5])

In [102]:
# Reversing an array
ar1[::-1]

array([ 5,  4,  3, 21,  1])

In [103]:
np.flip(ar1)

array([ 5,  4,  3, 21,  1])

In [104]:
# copy method and view method
ar10=np.copy(ar1)

In [105]:
ar11=ar1.view()

In [106]:
ar1

array([ 1, 21,  3,  4,  5])

In [107]:
ar10

array([ 1, 21,  3,  4,  5])

In [108]:
ar11

array([ 1, 21,  3,  4,  5])

In [109]:
ar1[1]=15

In [110]:
ar1

array([ 1, 15,  3,  4,  5])

In [111]:
ar10

array([ 1, 21,  3,  4,  5])

In [112]:
ar11

array([ 1, 15,  3,  4,  5])